main: me.hopper4et.DeathInventory
name: DeathInventory
version: 1.1
author: Hopper4et
api-version: 1.19
description: Plugin that show death coordinates and items that player lose.

commands:
  deathinv:
    description: show death coordinates and items that player lose.
    usage: /<command>
    aliases: deathinventory
    permission: deathinventory.command
permissions:
  deathinventory.command:
    default: true
  deathinventory.showinventory:
    default: true
  deathinventory.cantakeitems:
    default: op